### ISSUE TITLE
Change directory where subdomains are stored

### ISSUE THREAD

**Issue by crone11** [virtualmin/virtualmin-gpl#146]
Hello Dear Sir or Madam!

I am wishing to change the default home directory location for sub domains.

Currently it is set to the /home/domain/domains/subdomain and I want to set it to a different one like /home/subdomain or /home/subdomains/subdomain

If this is not possible please do a feature request think.

Thanks for read this.

**Comment by rostovtsev** [comment]
Hi,

If you want to change it to be outside of domain's root folder - I wouldn't recommend doing it, due to shared permissions among domain and sub-domains (I don't think it's even possible doing it naively in Virtualmin). 

From what you asked, it seems it would be better, if you just created separate virtual-server for a sub-domain, it would have run under different user/group, would be placed to a separate  directory under home and etc.
