### ISSUE TITLE
Virtual server select dropdown box sometimes has the wrong server selected.

### ISSUE THREAD

**Issue by alexbogias** [virtualmin/virtualmin-gpl#25]
Sometimes the drop down select box of virtual server has incorrect server selected after you reopen and old session. This may drive to incorrect server deletion or similar issues. 
Its hard to tell you how to reproduce. But when you have the remember me option enabled and with the latest browser versions caching system sometimes you may see the wrong server selected.
Virtualmin v6.01-3

**Comment by swelljoe** [comment]
I suspect this is a theme issue. I've seen it on Authentic, but not Virtualmin Framed Theme. Ilia has done a major overhaul of how things work in the new beta version of Authentic, which may or more not fix this. Can you try the latest 19.02 version of Authentic theme and let me know if you can reproduce the issue?

I think you can use the theme update function to get the latest development version: Click Theme Configuration (the gears icon either in the little quick menu on the bottom-left, or the gears that appear when you hover over the theme version in the system dashboard), and scroll to the bottom and click "Force update theme" and choose "Latest development version".

There are a few minor quirks in the new version as well (though it's also remarkably faster), which is why it isn't shipping as the default theme yet, but if you find they're more problematic than this issue, it's possible to roll back.

**Comment by alexbogias** [comment]
Yeah this is true. I never saw it happen with the old Framed Theme. Its definitely a theme issue. I already installed the latest dev version 19.02-git-201711102348 and didn't happened yet. I ll keep you posted...

**Comment by alexbogias** [comment]
I didn't notice this happed again.. I ll let you know I will...

**Comment by alexbogias** [comment]
It is still seems to working fine on the latest updates!
