### ISSUE TITLE
Ubuntu apt sources don't include webmin packages

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-gpl#285]
When installing virtualmin on Ubuntu 18.04 via the recommended way `wget http://software.virtualmin.com/gpl/scripts/install.sh` webmin is included, but the webmin updates are not offered via apt.

During installation a file `/etc/apt/sources.list.d/virtualmin.list` is created with two entries

```
deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-bionic main
deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal main
```

but these sources don't seem to include webmin packages.

When logging in to virtualmin I am greeted with a warning to update webmin:
![Screenshot 2021-05-03 at 09 55 47](https://user-images.githubusercontent.com/45786226/116853111-ca0b2f80-abf5-11eb-9c9f-318198e255b0.png)

No matter how often I execute `apt update` / `apt upgrade` there are no updates for webmin offered

Seems to be related to https://www.virtualmin.com/node/67942

**Comment by swelljoe** [comment]
The universal repo contains Webmin packages. Current package in that repo is 1.973.

**Comment by swelljoe** [comment]
The bug here is that Webmin is offering to upgrade to a package that doesn't exist in the repos it knows about. I'll talk to Jamie and Ilia about that.

**Comment by iliarostovtsev** [comment]
> The bug here is that Webmin is offering to upgrade to a package that doesn't exist in the repos it knows about. I'll talk to Jamie and Ilia about that.

I don't see this bug. Joe, does it happen on your side?

Unless file `/etc/webmin/webmin/root.acl` contains `disallow=upgrade`, this message should not be displayed.

I guess, perhaps @PitWenkin is not logged in as _root_ user but some other root-capable user instead?

**Comment by PitWenkin** [comment]
> I guess, perhaps @PitWenkin is not logged in as root user but some other root-capable user instead?

Indeed. For security reasons I created a user with same settings/rights as _root_. _root_ user has login disabled…

**Comment by iliarostovtsev** [comment]
> Indeed. For security reasons I created a user with same settings/rights as root. root user has login disabled…

How exactly did you create that user?

**Comment by iliarostovtsev** [comment]
I see this issue is happening if you create a new **Webmin Privileged** user using **Webmin Users** module. I would suggest cloning existing _root_ user, if you need to preserve the ACLs.

You can easily work-around the problem by creating mentioned _.acl_ file for the given user.

@jcameron Jamie, can we also check upon new privileged Webmin user creation (not cloning) if _root.acl_ file should be inherited with `disallow=upgrade` for a newly created user? Or it would be better to have a fix on `get_webmin_notifications` sub?

**Comment by jcameron** [comment]
Really we shoudn't be displaying that message about a new Webmin version on any system that was installed from another repo, like Virtualmin. Instead it should come in via the regular package update process.

This is typically prevented by having `nowebminup=1` in `/etc/webmin/config`

**Comment by PitWenkin** [comment]
I did not know cloning was possible (I'm following a personal how-to which is some years old).

I simply create a new user via **Webmin Users** where I leave everything on default, and make all modules available.

Current content of `/etc/webmin/root.acl` 
```
root=/
fileunix=root
gedit2=
gedit_mode=0
nodot=0
feedback=2
uedit=
negative=0
uedit_mode=0
uedit2=
readonly=0
otherdirs=
gedit=
rpc=2
webminsearch=1
```

and content of the acl of the user I 'm actually using:
```
feedback=2
webminsearch=1
uedit_mode=0
uedit2=
gedit=
root=/
fileunix=root
otherdirs=
gedit2=
nodot=0
uedit=
readonly=0
rpc=2
negative=0
gedit_mode=0
```

Neither has `disallow=upgrade` nor `get_webmin_notifications` and I definitely did not mess with the _root_ user, except disabling login by setting password to `no password accepted` via **Webmin Users** - interface

The content of `/etc/webmin/config` looks like this:
```
cache_mods=virtual-server
find_pid_command=ps auwwwx | grep NAME | grep -v grep | awk '{ print $2 }'
by_view=0
passwd_cindex=2
lang=en
real_os_type=Ubuntu Linux
path=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
ld_env=LD_LIBRARY_PATH
passwd_mindex=4
logfiles=1
referers_none=1
log=1
cache_size=52428800
real_os_version=18.04.5
theme=authentic-theme
mobile_theme=authentic-theme
passwd_uindex=0
os_type=debian-linux
md5pass=1
product=webmin
passwd_pindex=1
passwd_file=/etc/shadow
tempdelete_days=7
os_version=9.0
webprefix=
```
No `nowebminup=1` in there either.
I removed stuff regarding virtualserver (ownmods_…/realname_…)

**Comment by iliarostovtsev** [comment]
> This is typically prevented by having nowebminup=1 in /etc/webmin/config

Okay, we will fix this for the new installs - https://github.com/virtualmin/Virtualmin-Config/commit/ad76c11cf523b229502af8b1dc78fbbc2d239b04

**Comment by PitWenkin** [comment]
So I should put `nowebminup=1` in `/etc/webmin/config` on existing servers to remove the notification?

When will Webmin 1.974 be available via apt ?

**Comment by iliarostovtsev** [comment]
> So I should put nowebminup=1 in /etc/webmin/config on existing servers to remove the notification?

Yes.

> When will Webmin 1.974 be available via apt ?

A bit later.

**Comment by PitWenkin** [comment]
New installation on Ubuntu 20.04 still has this behaviour.

Shows 1.979 as available while 1.973 is installed.

When will 1.974, which fixes this(?), be available via apt? 😉

**Comment by swelljoe** [comment]
Ilia/Jamie, why is the dashboard still showing a version that's not available in the available repos? Can we stop doing that?

**Comment by iliarostovtsev** [comment]
I remember I fixed that and new installations won't have such problem.

Jamie, what about _root_ capable users, which don't have correspondent Webmin user and/or don't have _`disallow=upgrade`_ set? Could they check for _`disallow=upgrade`_ option from ACLs of regular _root_ user instead? Otherwise all existing Webmin users logged in using root capable account will still see upgrade prompt.

**Comment by swelljoe** [comment]
I don't even understand why it would check for updates from a source that is unavailable, ever for any users. It doesn't make sense.

**Comment by iliarostovtsev** [comment]
> I don't even understand why it would check for updates from a source that is unavailable, ever for any users. It doesn't make sense.

Either it should be **`nowebminup=1`** set on the Webmin config or **`disallow=upgrade`** on the user's ACLs, otherwise it will check for the new version on Webmin site, and suggest installing an upgrade (on the Dashboard) using _rpm_, _deb_ or _tar_ package, depending on what is currently installed.

**Comment by swelljoe** [comment]
But then it doesn't work! It's checking for an update from a source that it won't use when it actually tries to upgrade. It shouldn't require an option to be set to behave sanely.

So, two issues here:

1. If the user has Virtualmin installed, package updates should come from the package manager, and Webmin shouldn't even check webmin.com for updates.
2. If Webmin offers to upgrade based on a check of Webmin.com, it should _use_ Webmin.com for the update.

There are two bugs. One is that users other than root who have root-level access due to sudo are being offered an update they shouldn't see. The other is that Webmin offers to update based on information from Webmin.com but fails to do so, because it then doesn't use the package from Webmin.com to perform the upgrade. On a Virtualmin system, the user should never see the second problem (because Webmin shouldn't even look at Webmin.com if it has a yum/apt repo to update from), but the second problem is still a problem.

**Comment by iliarostovtsev** [comment]
We just discussed few things internally with Joe.

@PitWenkin So, if you click this _Upgrade Webmin_ 
button from a Dashboard, does upgrade happen to work?

**Comment by PitWenkin** [comment]
@iliarostovtsev on my local dev environment:
![Screenshot 2021-07-06 at 07 31 38](https://user-images.githubusercontent.com/45786226/124547855-17419280-de2d-11eb-8c6c-f3c8641d06df.png)

Everything seems to work fine (there was a popup about lost connection to the server, which should be because webmin restarted itself?)
![Screenshot 2021-07-06 at 07 33 12](https://user-images.githubusercontent.com/45786226/124547871-1f013700-de2d-11eb-8a86-375c690676d8.png)

After the update I'm forced to re-run the post installation wizard (Both Webmin and Virtualmin menus are emtpy):
![Screenshot 2021-07-06 at 07 33 38](https://user-images.githubusercontent.com/45786226/124547899-2f191680-de2d-11eb-8d7c-28d9ad945f76.png)

The configuration re-check failed due to BIND DNS with missing 127.0.0.1 in DNS Servers. But is not used anyway.
![Screenshot 2021-07-06 at 07 36 58](https://user-images.githubusercontent.com/45786226/124547818-08f37680-de2d-11eb-997b-5ed27326893e.png)

Still works after a reboot

**Comment by swelljoe** [comment]
Well, hell. That's that what I thought would happen at all.

So, there's still a bug but it's not the one I thought it was.

**Comment by iliarostovtsev** [comment]
> Everything seems to work fine (there was a popup about lost connection to the server, which should be because webmin restarted itself?)

Yes.

> Both Webmin and Virtualmin menus are emtpy:

The missing menu could happen, and could easily be fixed with clearing cache:

![image](https://user-images.githubusercontent.com/4426533/124567550-c93c8700-de4c-11eb-9a97-7b0cad8d800b.png)

..however, @jcameron I think we should delete all menus cache in post-install scriplet.

> After the update I'm forced to re-run the post installation wizard 

This is something completely bizarre, and should _never_ happen. I will try to reproduce it later today, after I reinstall and re-setup my main PC OS.

**Comment by PitWenkin** [comment]
> > After the update I'm forced to re-run the post installation wizard

> This is something completely bizarre, and should never happen. I will try to reproduce it later today, after I reinstall and re-setup my main PC OS.

I did the initial setup of the server on Ubuntu 16.04, which has been upgraded to 18.04 and 20.04. All has been done with the default `root`-user. I only created a new user on that particular machine for this test … so maybe it's user related?

**Comment by iliarostovtsev** [comment]
>  I only created a new user on that particular machine for this test … so maybe it's user related?

Oh, you perhaps forgotten to assign available modules for that user.

> If the user has Virtualmin installed, package updates should come from the package manager, and Webmin shouldn't even check webmin.com for updates.

Joe, done. 

I have given it a closer look and added a [patch](https://github.com/webmin/webmin/commit/aa4bfae56904718babe1db509d8ab46c7cdae911) to address it for the current installs as well. The idea is simple. When a new privileged Webmin user is created (not cloned from existing _`root`_), then upgrade notice will not be displayed as it happens right now, as long as default _`root`_ user has **`disallow=upgrade`** set on ACLs.

 However, if for some fancy reason there should be specific user on the system that runs upgrades it can be done by setting **`role=upgrader`** and/or using **`allow=upgrade`** option. Finally, if any root capable user must be able to run Webmin upgrades using Webmin repos, then **`disallow=upgrade`** can simply be removed from ACLs to make it happen.

Besides, clean Virtualmin installations will have it disabled for all users system-wide.

**Comment by PitWenkin** [comment]
> Oh, you perhaps forgotten to assign available modules for that user.

I assigned **all** available modules

**Comment by PitWenkin** [comment]
> After the update I'm forced to re-run the post installation wizard (Both Webmin and Virtualmin menus are emtpy):

I just re-enabled the update via GUI-thingy on a test server, to check if a newer version of webmin fixes some dovecot/postfix certificat bugs.
I again had to re-run the post installation wizard as well as the configurstion re-check and refresh.
