### ISSUE TITLE
Adding new DNS zone .. .. BIND DNS domain failed

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-gpl#292]
O/S: RHEL 8.3
Virtualmin: 6.16
Webmin: 1.973

I have created a test KVM instance from a RHEL 8.3 base image, installed Virtualmin and when I try and create a new virtual server, BIND fails to create the zone file for the virtual server.

```
In domain testing.mydomain.co.uk
....

Creating mailbox for administration user ..
.. done

Adding new DNS zone ..
.. BIND DNS domain failed! : Failed to open /var/named/chroot/var/named/testing.mydomain.co.uk.hosts for writing : No such file or directory

Adding new virtual website ..
.. done

....
```
Under the BIND DNS section of Webmin, I see the following:

`Warning : The chroot directory /var/named/chroot that Webmin thinks BIND is using may be incorrect. The zone files for 1 domains could not be found.`

BIND is running:

```
systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2021-05-17 19:41:56 BST; 20min ago
 Main PID: 71710 (named)
```

However Webmin doesn't detect it as running:
![Screenshot 2021-05-17 at 20-03-47 BIND DNS Server — Webmin 1 973 (Redhat Enterprise Linux 8)](https://user-images.githubusercontent.com/389303/118542576-16548480-b74b-11eb-8762-769235b26e25.png)

**Comment by chris001** [comment]
When you click on the `module configuration` page, what's the `chroot` directory set to ?

**Comment by pixel-paul** [comment]
`Chroot directory to run BIND under: None`

![Screenshot 2021-05-17 at 20-41-24 Configuration — Webmin 1 974 on is-73413 (CentOS Linux 7 9 2009)](https://user-images.githubusercontent.com/389303/118546817-6255f800-b750-11eb-99c5-a4daaa6bc6dc.png)

**Comment by pixel-paul** [comment]
The issue here is that Virtualmin is setting a chroot directory to run BIND under when it should be set to 'None'

Thanks @chris001.

**Comment by swelljoe** [comment]
Virtualmin didn't do anything of the sort. Webmin decides where BIND files get created, based on the configuration. Virtualmin does all BIND configuration through Webmin API calls and has nothing to do with paths.

I don't know what the default behavior is, but Webmin should be able to manage your zones whether they are in a chroot or not (and Virtualmin should be able to use Webmin to manage them, too) as long as the config is right.

I guess the confusion is why isn't the config right? Were there errors during installation of Virtualmin? During the BIND step of virtualmin-config, it creates all the necessary directories for whatever configuration the BIND module is in (whether chroot or not). It seems like chroot/no chroot got switched at some point after install, or the config failed to do its job (but there should have been errors and a non-green OK/checkmark during install, if so).

I don't know if the default is to chroot or not to chroot on RHEL 8 or whether Webmin is configured to use a chroot or not on fresh install, which is baseline information for figuring out where the problem is.

**Comment by chris001** [comment]
Running `bind9` under `chroot` is more secure against hackers trying to get into your server by exploiting buffer overrun or stack overflow bugs in `bind9` and should be the default config which Virtualmin or Webmin configures on the server, and it should be made dead easy for server master admin to upgrade to `chroot` at any time if it wasn't running under `chroot`.  With that out of the way, here's one of my servers' `bind9` configs, it works, the server is running debian 8 jessie:
![bind9 paths virtualmin issue 292](https://user-images.githubusercontent.com/259416/118576679-fe82fd80-b756-11eb-95fc-da98cf659e44.png)

**Comment by swelljoe** [comment]
It isn't all that much more secure. chroot as security feature is mostly superstition (though chroot is no longer actually dangerous as it used to be before Linux capabilities existed to allow chrooting without starting as root). But, I have vague recollection that it's the default on CentOS/RHEL, so I don't know what happened that would make it get out of whack.

**Comment by pixel-paul** [comment]
The starting image was a base RHEL 8.3 image. I then ran 'Install Virtualmin' using Cloudmin. No errors were generated.

I wasn't sure at the time if this was a Webmin issue, so thanks for the correction. 

Some further digging into this and I note that the `bind-chroot` package needs to be installed to run BIND under chroot on RHEL 7 & 8 (ref, you'll need a RH account: https://access.redhat.com/articles/770133). However Virtualmin does not install this package:

```
dnf list installed "bind-chroot"
Updating Subscription Management repositories.
Error: No matching Packages to list
```
