### ISSUE TITLE
Replacing procmail

### ISSUE THREAD

**Issue by fakemoth** [virtualmin/virtualmin-gpl#298]
Are there any plans to replace the unmaintained procmail and officially supporting something else in Virtualmin? If it is the case, what exactly should we expect?

**Comment by jcameron** [comment]
Not at the moment - as long as procmail continues to be available in common Linux distributions.

**Comment by swelljoe** [comment]
Dovecot supports Sieve, and it's a reasonable replacement for most functions of Procmail, so it's probably where we'll end up. But, as Jamie notes, it's not imminent.

**Comment by fakemoth** [comment]
Thanks for clearing that, looking forward for news about this.

**Comment by marclaporte** [comment]
Procmail was dead but came back to life **after 19 years of inactivity**. I don't remember ever seeing that. Not even close. Usually after even a few years, it's pretty much a certainty the project will not be revived.

- https://github.com/BuGlessRB/procmail/commits/master
- https://en.wikipedia.org/wiki/Procmail

I still favor Sieve because of broad support by mail clients: http://sieve.info/

But I am very pleased we are no longer counting on a dead project.

**Comment by marclaporte** [comment]
For the record: [we](https://wikisuite.org/) will experiment with adding Sieve as an extra option available to end users. Once this works well, we'll have the option of progressively using for Virtualmin. I realize that replacing Procmail and migrating data is much more complex (and beyond the scope of our current experiment).

FYI: https://github.com/dovecot/tools/blob/main/procmail2sieve.pl

**Comment by marclaporte** [comment]
[Procmail considered harmful](https://anarc.at/blog/2022-03-02-procmail-considered-harmful/) by The Anarcat
