### ISSUE TITLE
Confused about the way to upgrade virtualmin

### ISSUE THREAD

**Issue by Vagrantin** [virtualmin/virtualmin-gpl#52]
Debian 9
Webmin 1.880 ( installed via apt)
Virtualmin 6.01 ( installed as a module from Webmin interface)

I have looked around to understand how i can safely update Virtualmin and I don't see any case fitting my situation.

First from the interface, the only info I have is that my Virtualmin version is too old, but nothing to perform the upgrade of the module.

I looked in ``Webmin Configuration > Webmin modules`` but looking in ``Standard module from www.webmin.com`` the Virtualmin package doesn't exist...

I found the Debian repository, but because the package was installed originally has a module I'm afraid to break everything going to that path for an upgrade..

From what i understand the ``install.sh`` script his not design to perform upgrade has the script name stipulate :) 

So from here what would be the best way to upgrade Virtualmin is it safe to switch to ``apt`` even if it has been installed has a module ? 
Is there another method I'm not aware of ?

Thanks for the clarification!

kind regards

Matth

**Comment by swelljoe** [comment]
Yes, it is safe to switch to apt, assuming your Webmin was installed from a deb package and not a tarball. There's a sorta secret flag `--setup` to the install.sh that will setup the apt repo for you, if the OS is supported. Make sure you have the latest version of install.sh, as it is somewhat new.

Backup your /etc/webmin directory first just in case.

You'll then have to manually install the webmin-virtual-server package (`apt-get install webmin-virtual-server`), as the wbm module isn't known to apt/dpkg, so it won't know there's an upgrade available.

If you installed Webmin from a tarball, you will have to stick with wbm for your modules. We have wbm repos for Virtualmin GPL and Pro, too, but let's hope you don't need that.

**Comment by Vagrantin** [comment]
Ok thanks for the clarification,

Looking at the [repo](http://software.virtualmin.com/gpl/), I couldn't found the one for strech(Debian 9) should I use the Jessie one ?
Also once I have backup /etc/webmin in case of a rollback, it only consist of putting back the content of the folder right ?

Thanks for the help.

Matth

**Comment by swelljoe** [comment]
You're looking in the wrong place. There is a stretch repo, and the jessie repo would not be compatible.

`install.sh --setup` will set up the right ones for you (the `--setup` flag does nothing but setup the apt repositories...it doesn't install anything or change anything), which is what I recommend; you actually need virtualmin-universal, and possibly *not* virtualmin-stretch, if you already have Virtualmin up and running and websites/mail/DNS configured (and if you *don't* have websites configured, you should start over with a fresh OS and use the install script to set everything up for you, because you've only got about a third of a Virtualmin system, right now...which is fine, if you know you just want the third you already have). But, it's harmless to have virtualmin-stretch enabled as well, it's just not where virtualmin updates will be coming from.

The current Virtualmin repos are in: http://software.virtualmin.com/vm/6/gpl/apt

virtualmin-universal is where the actual Webmin modules reside. They are all in pure Perl, and so are not distribution dependent...so, all debian versions use the same repo.

virtualmin-stretch contains some metapackages that work with the install script to install all of the dependencies of a full Virtualmin system, and a couple of binary packages that aren't provided by Debian OS repos, which may or may not be useful for you, depending on whether you'll be managing your mail with Virtualmin.

So...maybe we should figure out where you are currently; this might be a bad idea, just because you're thinking you've got Virtualmin installed, when you really only have one Webmin module (there are a dozen or so Virtualmin modules, a stack of OS-provided dependencies a mile long, and a virtualmin-config package that sets all those services up in a way that's optimal for virtual hosting). Are you already hosting domains with Virtualmin and are you happy with the way everything is configured?

**Comment by Vagrantin** [comment]
Oh okay, I had no idea about all the implication, so here are all the information I can provide based on my little understanding of Webmin/Virtualmin hopefully I don't miss anything.

Operating system | Debian Linux 9
Perl version | 5.024001
Path to Perl | /usr/bin/perl
Apache version | 2.4.25
PHP versions | 7.0.19
Logrotate version | 3.11.0
MySQL version | 10.1.26-MariaDB-0+deb9u1
ProFTPD version | 1.35
Webmin | 1.880
Virtualmin | 6.01

For recall Webmin was installed with apt and Virtualmin as a Webmin module.
_The usage is quite simple :_
**Webmin**
Server administration
**Virtualmin**
Apache administration
Ftp server

I don't host domain names/mail server/user management or any other kind tools.
I'm able to upgrade Webmin from the interface, but Virtualmin is only tell me it's an old version but no clear upgrade path for me.

Hope this is clear enough

Thanks for the help.

Matth

**Comment by swelljoe** [comment]
If you're happy with the way Virtualmin is currently configured, and with the features you have setup, then just run `install.sh --setup` and then `apt-get install webmin-virtual-server`. You'll be done. That will enable the Virtualmin repos, and install the latest package.

**Comment by Vagrantin** [comment]
All clear now, thanks for the help !
Matth
