### ISSUE TITLE
Make the distinction between global virtualmin settings and vserver-specific configuration clearer in the sidebar

### ISSUE THREAD

**Issue by nekohayo** [virtualmin/virtualmin-gpl#573]
Here's an idea for a potential UX improvement.

In the sidebar I always find it difficult to see at a glance (if not downright confusing in general) whether I am the config of a specific virtual server, if I am affecting the global config of Virtualmin. Or oftentimes, I want to be looking for global things that would affect all servers, but end up in the wrong (vserver-specific) section.

The sidebar doesn't really clearly distinguish between the two, so you're left "guessing" that the lower half is for global settings, but even now I am presuming this, although my guess is probably correct (I hope).

The upper half has the vserver's (sub)domain selector combobox widget that _kinda_ acts as a header, but the lower half after the searchbar (why isn't the searchbar global for the whole sidebar anyway?) doesn't have any heading.

Some potential ideas:

* Giving the global virtualmin settings sections a different background color/shade?
* Putting a separator and heading saying "Global VirtualMin settings"
  * Also adding a heading saying something like "vServer / sub-server settings" or "Settings for $vserver_nickname" for consistency?
* Alternatively, maybe it could have two tabs at the top of the VirtualMin sidebar, under the "VirtualMin" tab, to differentiate between global and vserver-specific settings?

And overall I'd like to see the search feature moved to the top of the sidebar and making its scope global (unless you're using tabs), while preserving headers when filtering results?

**Comment by jcameron** [comment]
I kind of like the idea of a different color scheme for global vs local settings ... @iliajie is this something that could be implemented in the theme?

**Comment by swelljoe** [comment]
Color alone is not accessible.

**Comment by iliajie** [comment]
> In the sidebar I always find it difficult to see at a glance (if not downright confusing in general) whether I am the config of a specific virtual server

Isn't specific virtual server selected by the dropdown at the top of the navigation menu?

> Or oftentimes, I want to be looking for global things that would affect all servers, but end up in the wrong (vserver-specific) section.
> The sidebar doesn't really clearly distinguish between the two, so you're left "guessing" that the lower half is for global

Yes, the lower part is for "global" settings. I don't see how this can be confusing, as the search bar acts as a logical separator.

> but the lower half after the searchbar (why isn't the searchbar global for the whole sidebar anyway?

Search bar represents the beginning of the global section, and have it located at the top of the global section is the best possible solution in such design.

> Giving the global virtualmin settings sections a different background color/shade?
>> I kind of like the idea of a different color scheme for global vs local settings

No, I don't think it's a good idea! 

> And overall I'd like to see the search feature moved to the top of the sidebar and making its scope global (unless you're using tabs), while preserving headers when filtering results?

You are welcome to provide a visual mockup for your suggestions.

**Comment by nekohayo** [comment]
Here's a quick-and-dirty mock-up for the simplest approach, that I made simply by toying around with Firefox's web inspector tool:

![image](https://github.com/virtualmin/virtualmin-gpl/assets/479401/b6b12430-6985-4075-8b9b-1935f4be4cc7)

I did not bother to try to make a "darker shade of blue" background for the global settings area because that would be a more complicated hack, but you could probably imagine that, and it's maybe not necessary if using headings like I'm doing here... 

First/upper part of my mockup (yes, it's absolutely ugly hacky stupid HTML code I have done here, but it's just for the sake of the mockup, certainly you will come up with something that properly matches your code architecture):

```
<ul>
<b style="color:skyblue; margin:10px; display:block; text-align:center;">
vServer configuration for…</b>
</ul>
```

Second/lower part of my mockup (which also (ab)uses border styling to hack a subtle dotted separator just above the heading):

```
<ul>
<b style="color:skyblue; margin:10px; display:block; text-align:center; border-top:1px dotted white; padding-top:15px; margin-top:15px;">
Global VirtualMin settings</b>
</ul>
```

I used a "skyblue" color on a whim, to differentiate the headings from regular menu items by not having everything be "white". Gray wouldn't work, too dark and wouldn't match the blue hue of the sidebar. The funny part is, this whimsical "skyblue" color even works without additional changes with the dark variant of your official theme:

![image](https://github.com/virtualmin/virtualmin-gpl/assets/479401/cc7b60ae-a8d1-4293-aa48-50e40d9af390)

**Comment by marclaporte** [comment]
Related discussion: https://github.com/virtualmin/virtualmin-install/issues/42#issuecomment-813236162

**Comment by iliajie** [comment]
Also here https://github.com/virtualmin/virtualmin-gpl/commit/b05db45b96dc2402b55ef98ee4103ba99b34284e#commitcomment-118145500

**Comment by jcameron** [comment]
I wouldn't object to a separator/header for global options to make it clearer.. Or maybe color-coding on the left menu.

**Comment by iliajie** [comment]
> I wouldn't object to a separator/header for global options to make it clearer.

Currently, search bar acts as a logical separator between virtual server and global options

**Comment by nekohayo** [comment]
> Currently, search bar acts as a logical separator between virtual server and global options in Authentic theme.

That is implicitly obvious to you (developers who know how things are wired up in the backend), but it is not explicitly obvious (particularly to new users trying to find their way around and understand the application).

Additionally, for future-proofness (separate issue, I know...), I really don't see why the search feature should only scoped to those global virtualmin settings instead of both the global and vserver-specific settings (or even all three areas: vserver, virtualmin global, and webmin!). If it were to no longer be restricted to that "lower half only" scope in the future, then it wouldn't make as much sense for it to sit in the middle of the menu's two sections. In my humble opinion, a search widget isn't really supposed to serve as a replacement for explicit context; but since search is not truly global at the moment, I haven't moved it in my mockup.

**Comment by iliajie** [comment]
> I really don't see why the search feature should only scoped to those global virtualmin settings instead of both the global

As the search bar acts as the separator, it also connects "top" and "bottom", meaning it provides results for domain related links, just as system settings links. Not from Webmin though, as it's a separate tab. Note that I'm talking about autocomplete search feature, because search using server (when `Enter` is hit in the search bar) provides results across the whole system.

> but since search is not truly global at the moment, I haven't moved it in my mockup.

The search (autocomplete) provides results for the whole visible tab.


> That is implicitly obvious to you (developers who know how things are wired up in the backend), but it is not explicitly obvious (particularly to new users trying to find their way around and understand the application).

I agree that it may not be clear at first .. probably, the better solution would be is to use Intro wiget, the way Google and other companies do? For example, like [Intro.js](https://introjs.com/).

**Comment by nekohayo** [comment]
> The search (autocomplete) provides results for the whole visible tab.

Oh, that was really not obvious to me until you mentioned this now, specifically because it is positioned in the middle instead of the top, I assumed its scope was limited to the items below the search field.

My recommendation then would be to:
* Use headings as clear section separators
* Move the search field to the top, above the proposed 1st heading
* Make the current "autocomplete as a popoover widget" search a "filtering" search instead, i.e. something that live-filters the sidebar's contents (while still showing the headings in the filtered output). It would be much cleaner visually, as a filtering search simplifies what users have to look at (see example videos below), whereas the current autocompletion popover just adds additional visual stuff on top of an already heavily loaded sidebar.

> [...] probably, the better solution would be is to use Intro wiget [...]

I believe adding a tour-style tutorial is not a substitute for the UI being clear at all times, whenever possible. Besides, it would probably be more complicated (and an additional dependency) for you to implement and document vs what I am proposing here.

Besides their explicit/self-documenting nature, adding headings would have the added benefit that when you are autocomplete-filtering search results, you could still show those headings so the user could clearly see the context the search results are coming from.

Here's are two examples of live filtering search UIs...

...without headings (but with description abstracts!) :

[filtering search - g-c-c.webm](https://github.com/virtualmin/virtualmin-gpl/assets/479401/35a3aa0e-9754-4c8e-bd25-2df530da32da)

...with headings:

[filtering search - the other panel thingy.webm](https://github.com/virtualmin/virtualmin-gpl/assets/479401/84215a8a-f693-4c17-b126-eaf04b17ff24)

**Comment by nekohayo** [comment]
...alternatively, if you'd be interested in making it a truly global search, the search bar could be at the very top, above the Webmin vs Virtualmin tabs, and automatically replace the tabs by only "headings and sub-items results" while a filtering search query is active in the sidebar (later restoring the tabs' visibility when clearing the search). That's another way to look at it, which would alleviate the "Searching for 'mail' yield 18 config pages spread across 3 different sections, and you might not think of searching into Webmin specifically" problem.

**Comment by iliajie** [comment]
> * on top of an already heavily loaded sidebar, particularly with the dark stylesheet that uses the same background colors

You're right, this is bad, I agree. This is why I reworked the dark mode last week. If you install latest development version of the theme using Theme Configuration page, it will be more clear.

> alternatively, if you'd be interested in making it a truly global search, the search bar could be at the very top, above the Webmin vs Virtualmin tabs,

I understand that everybody is placing the search bar at the top. Perhaps, this is the reason you're looking for it to be there as well. But I don't see the logical reason for it to be at the top strictly, considering that there is only one search bar.

It looks pretty clear to me, e.g.:

<img width="260" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/ee493e2b-5d95-487f-8cd8-ae4fb195e011">
<img width="261" alt="image" src="https://github.com/virtualmin/virtualmin-gpl/assets/4426533/64b7507d-332f-4594-8ac4-39184a61da06">

Although, the contrast of the search bar and the dropdown should be still increased! I will fix that! I will also improve the section name contrast in the dark mode.

---

However, I don't like the idea of having sections titles or moving top bar at the top for Virtualmin. Webmin has the search bar at the top and reason for this is obvious, because it's only showing global/system configurations (one logical tree). Virtualmin on the other hand is displaying two, a virtual server configuration and global/system configurations.

Also, Webmin doesn't have a select dropdown at the top. If you move the search bar to the top, and right next to the dropdown select in Virtualmin, it will just look way to cluttered. 

Having it separated by `<hr>` is not much better/different than having it separated by the search bar. Not conventional, maybe, but human's brain can quickly make a different logic association. It's no-brainer.

I agree, that there is a lot of room for UI improvement but what you're suggesting doesn't look like an improvement to me. Sorry! And thank you for your suggestions anyway.

**Comment by swelljoe** [comment]
There's a lot of different ideas in this thread, but I want to boil down to at least a couple of problems they're trying to solve, and see if maybe we can focus on the smallest possible change that can solve the specific problems they're trying to solve. Reworking the whole menu is going to confuse a lot of users ("easy to use" is mostly "what I'm used to" for people who have been using software for any length of time).

The first problem, the initial source of this thread: It isn't clear that there are two sections, one applies to the selected virtual host, and the other applies to Virtualmin as a whole. This is a valid confusion, but I don't really like most of the suggested solutions to the problem. What's the least disruptive change we could make to solve this? Maybe add a header (forget about colors for now!) to the global section and a line where the search bar is now? I don't think the virtual host section needs a heading. It starts with the name of the domain in the dropdown. That feels like it is enough information about what immediately follows, to me.

The second issue is confusion over where the search bar is placed and what the search bar does. I agree this is a problem, too. I'm sure Ilia and I already had a conversation about what results the search bar returns; it absolutely should not just return Virtualmin results. If I'm searching for something, I probably don't know enough to know whether it's in Virtualmin or Webmin. It's user hostile to search for something you know exists somewhere in the product and have it not return any results; it's frankly infuriating. And, I also think the search bar should probably be somewhere else. In my theme, I'd moved it to a top menu bar (my theme had three page sections: top menu, left menu, and right content pane). A search field should be at the top or bottom of the UI. Middle of the menu doesn't make much sense.

So: If we're adding any section labels, just add a global label. Don't rely on color to differentiate things (it's not accessible to color-blind users, and it is tacky if not done with care). And, moving search bar probably is a good idea. The search bar is far more powerful in Authentic than in older themes, it only makes sense to give it a place of prominence that is consistent with other UIs that have a search feature.

**Comment by swelljoe** [comment]
But, also, doing nothing is better than making changes that aren't notably better/clearer. Because a changed UI is harder to use than one that doesn't change.

**Comment by shoulders** [comment]
## Background
- This is possibly one of the most important parts of virtualmin.
- The virtualmin menu is placed before the  webmin menu and this is why the search menu ends up in the middle. If you navigate to webmin you can see this clearly.
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/28a39eda-eee6-4aa8-bced-4d49df95ab6f)
- Menu improvements have been done since this issue was initially raised such as a new order for the menu items
- maybe now is the time just to relook and see what can be done here

## My `initial` thoughts

If I mention the same thing twice it is just helping me get my thoughts written doen.

1. **The search bar location**
   - it is in the wrong place, it should be at the top
   - I do not see it as a logical separator
   - because of the location in the middle I suspect the search box is extremely under used.
   - It is not obvious that the search box returns results for both virtualmin account and virtualmin server settings because it is in the middle and a normal user would expect it just to return the results from the section below the box.
   - The search box should be at the top and it would get used a lot more, I don't use the search box often because I keep forgetting it is there because at first glance it just appears as another menu item. You don't expect the search box to be in the middle ever.
   - if the search box just search the server/global settings then I could understand it's positioning.
2. **Separate sections not clearly defined**
   - the sections blend into one mainly because of using the search bar as a separator and it having the opposite affect.
   - the sections could easily be split without causing to much trouble and users above have come up with some suggestions.

## Some suggestions

- search box still present, simple white line separating the `user` and `admin` sections. This is nice and simple retaining the current menu system, but separating the 2 sections whilst also presenting the search box in a way that focus will be drawn to it.
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/b5bb8a5d-ab1e-4f82-89d4-501c5b1d9ddc)

- searchbox removed, simple white line separating the `user` and `admin` sections. This is nice and simple. this would be combined with moving the search menu to the top of the menu colum  
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/00c272ef-26e2-4e0b-9fb1-78f6ebd81732)

- search box at the top (option 1)
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/c16d2806-686b-43b2-b6a7-1a9622384a64)

- search box at the top (option 2)
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/eb6f8ce9-1da6-448f-9e52-55b41df4124a)

- search box at the top (option 3)
  ![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/20df52f4-d233-4fec-83c7-0bc9c039c581)

## My `Final` thoughts

- The search box at the top of the menu column looks a bit chaotic.
- The search box is not acting as a logical separator.
- The search box should stay where it is.
- The `user` and `admin` sections should be separated.

## Proposed solution

The segmentation of the two different sections should be done with a simple white line  between the `user` and `admin` sections which allows the menu to stay mainly untouched but achieves the following goals:

  - The 2 sections are clearly de-marked/separated.
  - The search box now becomes more prevalent and easier to focus onto which in turn will get more people to use it.

I would also enclose the search box with a border so it becomes a search box.

The outcome would be as below:

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/8bb35807-7d3b-4f33-9089-7f697367a724)

**Comment by iliajie** [comment]
I don't see absolutely _any_ benefit in changing navigation menu in the proposed way. Sorry.

I also don't care what and how others do it. I find existing layout to be pretty logical and straight forward. It's no brainer to understand what's going on after a few menu looking at the screen.

The search bar does act as a logical separator in this type of layout de-facto.

Thanks again! I will consider all these thoughts and suggestions in case of a large rework and only if we decide to move the search bar at the top of the screen. Although, it's a separate project.

**Comment by shoulders** [comment]
**This is just for other peoples reference** :smile:

![Menu-Separator](https://github.com/virtualmin/virtualmin-gpl/assets/319997/164bcc60-1cbb-4aac-be95-589f12d4a15a)

Authentic theme is extremely configurable so I have implemented the menu separator using JavaScript and CSS which is as follows

```css
/** Split Virtual Server and Global menu sections - v1.0 **/
 
/* Default/Day Mode - Section Separator */
#customSectionSeparator {
    width: 50%;
    margin-left: 25%;
    border-top: 2px solid #f5f0fffa !important;
    margin-top: 30px !important;
    padding-top: 30px !important;
}
 
/* Dark Mode - Section Separator */
html[data-theme="gunmetal"] #customSectionSeparator {
    border-top: 2px solid #00000054 !important;
}
 
/* Default/Day Mode - Search Box - Full border */
#webmin_search_form > div.form-group .form-control.sidebar-search {
    border: 1px solid #ffffff29 !important;
}
 
/* Dark Mode - Search Box - Full border */
html[data-theme="gunmetal"] #customSectionSeparator {
    border-top: 2px solid #ffffff1f !important;
}
```

```javascript
/** Split Virtual Server and Global menu sections - v1.0 **/
 
// Add in a div to allow correct sizing of Section Separator
function addCustomSectionSeparator()
{
    // Only add the Section Seperator if it does not exist and the Virtualmin menu is present
    if (document.getElementById("customSectionSeparator") == null && $(document.getElementsByName("dom")).is(":visible"))
    {
        // Get the container
        var container = document.getElementById("webmin_search_form").parentElement;
 
        // Build the code
        var myCreatedElement = document.createElement("div");
        myCreatedElement.setAttribute("id","customSectionSeparator");
 
        // Insert the code
        container.insertBefore(myCreatedElement, container.firstChild);        
    }
};
 
// Add Section Separator on initial page load (remember Virtualmin is a single page system)
$(document).ready(function()
{
    addCustomSectionSeparator();
});
 
// Add Section Separator on page changes (remember Virtualmin is a single page system)
$(document).change(function()
{   
    setTimeout(addCustomSectionSeparator, 500);
});
```
