### ISSUE TITLE
Installing Virtualmin Module From GPL Download Directory at Virtualmin.com Installs Pro Version

### ISSUE THREAD

**Issue by MSSEsq** [virtualmin/virtualmin-gpl#597]
Installing the Virtualmin module into Webmin by using the Webmin Configuration Install Module page to download from https://software.virtualmin.com/vm/7/gpl/wbm/virtual-server-7.7.gpl-3.wbm.gz installs the Pro version rather than the GPL version. The Dashboard lists Virtualmin version 7.7 Pro and displays:

>  Warning!
A problem was detected with your Virtualmin license :
An error occurred checking the licence : Missing serial number A renewal can be purchased at Virtualmin Shop (https://virtualmin.com/shop/)

Refreshing the license information changes nothing. I first reported essentially this same problem on October 3, 2021 in the Virtualmin Forum: https://forum.virtualmin.com/t/virtualmin-virtual-server-module-6-17-3-released/112354/12.

Operating system FreeBSD 13.2-RELEASE-p1 on amd64
Webmin version 2.021
Virtualmin version 7.7 Pro [Should be GPL version]
Authentic theme version 20.21

**Comment by swelljoe** [comment]
Oh, dang. Thanks for the heads up. I guess the create-module.pl script isn't respecting the --exclude flag. I'm looking into it.

**Comment by swelljoe** [comment]
Hmm...actually, my theory was wrong. I'm not sure what's happening. Maybe it's looking for a license file in `/etc/virtualmin-license` (which would be populated with `GPL` for both `SerialNumber` and `LicenseKey` in an install with the install script). It _shouldn't_ do that, but maybe that's what's happening.

I don't see any evidence the Pro version is what's in that path (when I download it and untar it, I don't see any Pro code and the version is 7.7, not 7.7 Pro). Very confusing.

I'll have to check with Jamie why this would be detected as Pro. The `get_module_version_and_type` function is maybe doing something wrong in the absence of GPL in the version in the module.info file or somewhere else. It's not clear to me how it tries to figure out, but it's detecting wrong rather than actually being the Pro version (if it were the Pro package, it'd have all those missing library functions).

**Comment by MSSEsq** [comment]
Joe,

	There is no “virtualmin-license” file in /etc or in /usr/local/etc, the latter being appropriate on FreeBSD. I also scanned the /usr/local/etc/webmin directory for any file named “module.info” and found none.

	Michael

**Comment by swelljoe** [comment]
`module.info` would be in `/usr/local/webmin/virtual-server`, which is where the module version string comes from. But, there may be some other magic happening. It's bug-like, though, for sure.

**Comment by iliajie** [comment]
> `module.info` would be in `/usr/local/webmin/virtual-server`, which is where the module version string comes from. But, there may be some other magic happening. It's bug-like, though, for sure.

Authentic theme is using this file and `version` key to detect if the installed Virtualmin version is Pro or GPL. I made it a long time ago, and there is probably a better way of doing it..

However, I expected `module.info` file format to be consistent.

For example, `.deb` and `.rpm` GPL versions of Virtualmin have `version` key set to:

```
version=7.7.gpl-3
```

The Virtualmin Pro package when installed with `.deb` and `.rpm` has it set to:

```
version=7.7
```

This `.wbm.gz` Virtualmin module in question has it set to:

```
version=7.7
```

I would expect it to be set similarly, i.e.:

```
version=7.7.gpl
```

**Comment by swelljoe** [comment]
That's not right. The wbm or from source installation of GPL would have a version of `7.7`. That's always been so.

**Comment by swelljoe** [comment]
Also, version detection shouldn't be happening in multiple places in different ways. Theme should be getting the info from upstream.

**Comment by iliajie** [comment]
Alright, agreed. Fixed for both theme and Virtualmin. Also added support for semantic Virtualmin versions.

**Comment by iliajie** [comment]
You're right. Here is [another fix](https://github.com/virtualmin/virtualmin-gpl/commit/07f84d1a63d69b38d09f1584727b981eb5cfedb7). Jamie, I don't know why you [changed](https://github.com/virtualmin/virtualmin-gpl/commit/d34bc6b2ee772decd213a73c4ea89398032f0e28) it back in time but it seems that we should only test for `pro` rather than looking for `gpl` ..

**Comment by MSSEsq** [comment]
I manually updated the installed virtual-server-lib.pl file to the version from the [latest fix](https://github.com/virtualmin/virtualmin-gpl/commit/07f84d1a63d69b38d09f1584727b981eb5cfedb7). The Dashboard is now behaving as it should in the GPL version. Thanks for fixing this.
