### ISSUE TITLE
Resetting Unix user changes file ownership

### ISSUE THREAD

**Issue by jcameron** [virtualmin/virtualmin-gpl#773]
@iliajie I'm opening this ticket to follow up on the issue you reported

I wasn't able to re-produce it though. Also, I suspect that the file ownership UID hasn't actually changed - instead, two users have ended up with the same UID, which causes `ls -l` to show the wrong username.

Can you reliably re-produce it? Also, what output do you get from the reset page?

**Comment by iliajie** [comment]
> I wasn't able to re-produce it though.

In order to reproduce it you'd need an FTP user that would have the same UID as the domain owner user.



> I suspect that the file ownership UID hasn't actually changed

Yes, that's exactly what's happening!

> which causes ls -l to show the wrong username.
> Can you reliably re-produce it? Also, what output do you get from the reset page?

Yes, I can. The "problem" is that the precedence of names for the same UID or GID is determined by their order in `/etc/passwd` or `/etc/group`. Before, the reset feature, was deleting and then re-creating a new user and group, the domain owner user was taken out of its place (deleted), which is always created before any other user in the domain, and later re-put at the bottom of the file. This made `ls -l` display the other, FTP username mapped to the same ID, that happened to be the first in the list after re-creation/reset.

---

I've applied your latest patch, and since the deletion no longer occurs, the initial issue doesn't happen again either.

**Comment by jcameron** [comment]
Oh shit that would explain it! It's a pity that the order in /etc/passwd matters, but I guess that as long as we preserve the order it will be fine.

I will mark this as closed!

**Comment by iliajie** [comment]
> I guess that as long as we preserve the order it will be fine.

Yeah, it shouldn't be a problem, because domain owner users is always created first.

Thanks!
