### ISSUE TITLE
Domain Protection should be only modifiable if user can delete and disable domain

### ISSUE THREAD

**Issue by willnode** [virtualmin/virtualmin-gpl#892]
Hello, I just noticed this protection feature is newly implemented: https://github.com/virtualmin/virtualmin-gpl/commit/82fceff5c8d5f8ee8e1045b610689b851ab37c2c

It's really good, can I think can cover one of my specific usecase. However, this one cause breaks our cleanup scripts, because one of my user just enabled this protection via UI and bypass our automated quota monitoring scripts. 

Our current workaround is toggling off this config each time before disabling/deleting script. But I like to see this configuration to appear **only** if that user can disable and delete domains. Would you agree?

**Comment by iliajie** [comment]
> But I like to see this configuration to appear **only** if that user can disable and delete domains.

It's complicated to lean one way or the other on this. The problem is that the master administrator always has access to delete or disable domains. In this case, they would be able to bypass the protection lock and potentially delete a domain that isn't meant to be deleted or disabled.

I think you should manually toggle the lock off to accommodate your specific scenario.

**Comment by iliajie** [comment]
However, as I reread your question, it makes sense to show this configuration option in UI only if a user has access to delete or disable the domain. I'll update this ticket with progress in a bit.

**Comment by iliajie** [comment]
This has been implemented for inclusion in the next Virtualmin release! Thanks!

**Comment by willnode** [comment]
Thank you @iliajie!

**Comment by iliajie** [comment]
You're welcome, Wildan!
