### ISSUE TITLE
virtualmin-gpl on github is really virtualmin-pro?

### ISSUE THREAD

**Issue by victimsofgaybullying** [virtualmin/virtualmin-gpl#9]
According to the module.info file when I forked this 26 commits ago it's virtualmin-professional.

I went back to using the gpl module "version=5.99.gpl" and diffed the pull request #8 because the virtualmin theme was nagging me about my non-existant license using this github version.

If the module.info file has "version=5.99" then it's probably still the pro version. I'll check after logging this issue.

Apart from more scripts, what's the salespitch for pro?

Rather than tweaking/hacking this github version to not nag for a license, I think it's more ethical for the maintainer Jamie to fix the licensing issue.

**Comment by swelljoe** [comment]
Yeah, we'll fix that; it isn't intentional. Thanks for the heads up! (And, it's not actually the pro version; just a bug in how it's checked.)

Anyway, it's an artifact of the way Virtualmin used to be developed before a few months ago (in a private repository...Pro and GPL were not separate repos back then, and the difference was in how they were packaged rather than what was in the repository). It should be easy to grab the git repo and run it (assuming you get the other bits into place...the config copied to the right place, and module added to the root ACL), so we'll work on that.

Pro has:

  - Reseller accounts, which can manage multiple independently owned domains; valuable in large organizations and hosting provider environments. Also useful if you want every app or domain or whatever to have its own system user but be managed by the same non-root user.
  - System analytics graphs. This one is slowly being merged into GPL, but it'll be a while, as we're also wanting to upgrade it to a new charting library.
  - Resource limits. Again, large organizations and shared hosting providers need this, individuals and web devs who manage their own servers often don't.
  - A few other random bits and pieces that probably aren't written down anywhere (but should be, if I ever find the time).
  - 100+ Install Scripts instead of the 8 or 9 in GPL. We're slowly moving a few more of those into GPL over time (WordPress went in with 5.99), but they're a huge amount of work to maintain and keep up to date, so we don't really know how to pay for their maintenance if we aren't getting paid for them.

The rule of thumb is: If it is primarily of use to larger organizations or people making money with Virtualmin, it might be a Pro feature. If it isn't (and even sometimes if it is), it's probably a GPL feature.  GPL is extremely functional all by itself; it is not, and never has been a "demo" style free version. It is, I believe, competitive with anything on the market (free or otherwise) in terms of functionality and flexibility. I wish we had a was to fund Virtualmin that didn't require a commercial version, but we tried several experiments over the years, and they all came up incredibly short (like bringing in <5% of what we need to sustain the thing over a span of years).

**Comment by victimsofgaybullying** [comment]
I'm unsupported everything (gentoo) and I rather finesse my own scripts installers.
I wonder how webapp-config in gentoo could be made webmin friendly. You'd get lots of free scripts updated for you ;)

I'm just using virtualmin as part of a ceph / ldap / distributed / cfengine etc hosting cluster to avoid censorship takedowns. 

I wont talk off topic but a it involves the establishment in Australia jailing Christians for religious vilification of OTOAustralia.org.au that admits on camera they do XYZ to children, and minority sexual preference judges who admit on their lawfirm blog they specalize in representing pedophiles and those who enabled them ruling in case law that those who abuse infants "must not be villified" because they said the magic words I AM XYZ they did it. Baah I already said to much, anyway [here's my 72 year old phd father doing an interview about it - hour 2](http://www.truthnews.com.au/web/radio/story/cultural_marxism_101), it's "mckee burns" in www.caselaw.nsw.gov.au too and yeah the rabbit hole goes much deeper. In simple terms I'm organizing a massresistance.org against the establishment that children are taught to love at kidsrights.org.au / unsafeschools.org and I've spent a decade researching what they are capable of, and it's even worse than Ahu Garib in some cases on a larger scale. 

I use fail2ban and everything I can do to use my systemadmin skills to mitigate DDOS. I need the clustering and that's why I chose webmin even though it's a small site for now, but I have to be prepared, because the way even the [Celebs are going](http://www.dailymail.co.uk/tvshowbiz/article-4690858/James-Woods-addresses-critics-controversial-tweet.html) anti-establishment microblogging services like gab.ai or more specalized neice markets might take off.

Anyway I definately can't say more, because we all know where this platform Github is based.

**Comment by victimsofgaybullying** [comment]
@swelljoe oh I forgot the best salespitch for virtualmin. Cloudmin with services client includes a free virtualmin. That is something I'm definately going to purchase if and when I get a dedicated server, also using the DOM0 (xen) or KVM host to do the database / clamav is a great performance boost. You can also offload crypto to a pci /dev/crypto board to KVM guests now, something I'll also be trying out at home.

**Comment by swelljoe** [comment]
The free license deal goes the other way; if you buy Virtualmin Unlimited ($20/mo or $200/yr) you get Cloudmin Connect ($4/mo or $40/yr) for free. That'd work with any number of Virtualmin servers (whether Pro or GPL) to allow use of Cloudmin Services for Virtualmin (which allows off-loading databases, spam/AV scanning, and DNS to one or more separate servers; very useful, nearly priceless really, for large operations, not as exciting for single-server deployments).

Let's not get sidetracked into a political discussion. I don't speak for other Virtualmin folks, I can only speak for myself, but I wholeheartedly support LGBTQ equality in a very active way (I march, I hold signs, I go to rallies, I talk to legislators, I visit my reps), and it sounds like you're rolling hard on a pretty bizarre conspiracy theory equating homosexuality with pedophilia and child abuse. If I'm misinterpreted you (I am unfamiliar with most of the topics you're discussing and it's way too late for me to wander down some Alex Jones conspiracy rabbit hole), I apologize. But, really...I'm pro-equality. I don't have any interest in being supportive of an anti-LGBTQ organization. And, I know that a lot of people who oppose LGBTQ equality use made up accusations of pedophilia, devil worship, etc. to demonize gay folks (e.g Pizzagate).

We obviously won't stop you from using our software; it is Open Source because we believe in access to communications tools for everyone. But...well, this sounds gross, and I don't really want to take part in the conversation you seem to want to have. I really don't think we're on the same team.

**Comment by victimsofgaybullying** [comment]
Yeah well it's case law not conspiracy theory. With something I wrote as well sourced as what I said from mainstream sources it couldn't be anything else. I just had to have the last word on the topic to prove it's no hairbrained conspiracy theory - unless the government has got into the business of publishing them.
https://www.caselaw.nsw.gov.au/decision/58b7789fe4b058596cba49b5
[My dad showed his plane ticket to vietnam](https://vi.scribd.com/doc/312715457/nodiscrim-criminal-gaymafia-pedo-extortionracket) to Wakefield the XYZ pedophilia normaliztaing judge proving he was there when he made the comment and Australia had no jurisdiction but Wakefield ruled, all Vietnamese internet users governed by Australian courts must respect anyone who says the magic acronym and is found guilty of sodomizing a child in An American court (Mark Newton / Peter Truong), it's called a diplomatic incident involving, because it was a Russian child involved. The real reason my dad was targeted by my gay stalker @garryburnsblog was because he did an interview with his son (https://www.youtube.com/watch?v=cWeotGNzBNw )about the special Pink-Triangle.org Waffen SS logo wearing http://facebook.com/policeglbti segregated gay apartied law enforcement officers, because homosexuals don't think regular police are good enough for them. After that the special gay police and special gay courts ran my father out of Australia too. Please don't deny NSW GLLO gay police proudly wear Waffen Nazi SS logos with pride, or you will be a holocaust denier. I'm a black triangle myself - political dissident and UNHCR confirmed political refugee on letterhead http://bit.ly/aurefugee2 [GLLO Special Gay segregated police because all normal police can't be trusted to do the bidding of the elite LGBTI is Harvard's best innovation in American government too](https://www.youtube.com/watch?v=q-33OiibADU)

I also got Tammy Lynne Charles (New Life IVF Thailand & more) and her gay son arrested in Cambodia for Human trafficking just like the example I gave before with Mark Newton and Peter Truong. If the LGBT lobby says don't hate human trafficking it's hate speech to complain if we do it - something is wrong with a society if it doesn't care about it children. Someone has got to fight to keep the world safe for children. I think it's a noble cause just like you think your is nobel. So we can agree to disagree.

You saw the link to his actual comment, and the internet archive saying what he said, yet it was refuted by the LGBTIXYZ judges.
Enough said. 
The interview with Jim Fetzer PhD (x2) of 911 scholars for truth would have shown that. 

We'll when I'm ready, I'm sure there will be plenty of anti-free-speech facists trying to remove my server from the Internet. 

If you see the comment on the pull request I did I've got a few patches in the pipeline over the next few months. The last of them being btrfs quota support, thought that could be implemented as a quota script and just blogged which is probably what I'll do. So consider the discussion finished on this topic and I'll keep it all from  on webmin source related. But do tell all your LGBT friends to have a crack at the box when I think my security work is done, if they don't mind being reported automatically to their ISP on genuine attempts to get in (fail2ban recidive).

**Comment by swelljoe** [comment]
Look, this is not the place. The topic of the conversation is Virtualmin. Says it right at the top. If you want to talk about something else, do it somewhere else. I've deleted your comments because they are wholly off-topic.

I believe that (until I'm able to sort out how to make it detect correctly without it) if you add a file called "/etc/virtualmin-license" containing the following:

```bash
SerialNumber=GPL
LicenseKey=GPL
```

I think it'll get it right and won't complain about the license. I can't think of where else it would be looking.

**Comment by victimsofgaybullying** [comment]
I'll post those two comments on pizzagate and your reply, I guess that's the place, but now you know if you win the argument the truth must be censored. Delete your comment too giving the false perception I'm nuts for opposing my father being found guilty of disrespecting convicted XYZ pedophiles or I'll do that.
Let him have the last word not me.
http://www.truthnews.com.au/web/radio/story/cultural_marxism_101 (hour 2). Was it so bad I said caselaw not conspiracy theory? https://www.caselaw.nsw.gov.au/decision/58b7789fe4b058596cba49b5

Thanks for that fix. It's also looking at the version number in module.info being prefixed with a .gpl according to my grepping.
